### ISSUE TITLE
[feature] hide refresh button for expose that are readonly?

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#115]
There seems to be more properties that can;t be refreshed because there is no get converter for them. We should hide the button for them.

We might need a new property in the expose API though, as some readonly properties can be queried but not most :(

@koenkk ☝️  ?

**Comment by Koenkk** [comment]
> We might need a new property in the expose API though, as some readonly properties can be queried but not most :(

Which ones are these?

**Comment by sjorge** [comment]
![](https://user-images.githubusercontent.com/379665/98137385-3664da80-1ec2-11eb-999b-284766614132.png)

The little icon is to do a /get request for them, but that obviously doesn't work for most of the values here as there is no /get converter, I see no way this is currently exposed in the API though.

We expose if something is writable or not... but not of something is queryable.

**Comment by Koenkk** [comment]
I see, it means those get converter still have to be added.

**Comment by sjorge** [comment]
Is it possible for everything to get a /get converter? Then maybe we should just add them but if not, exposing if one is available seems fine. I'd imagine things like lqi don't have a get converter at all?

**Comment by Koenkk** [comment]
@sjorge yes you are right, I think the problem here is that `access: r` currently does not mean you can do a get but that the value will be present in the payload, there is currently no `access` that describes that a property can be `/get`. Maybe we should add a fourth access mode called `none` (which we will use for e.g. occupancy of a Xiaomi RTCGQ01LM since it cannot be read nor written).

**Comment by sjorge** [comment]
@Koenkk I think that would work yeah... @nurikk or do you have a better idea?

**Comment by nurikk** [comment]
Done

**Comment by pedrolamas** [comment]
Is this fixed in the latest z2m 1.16.2 ? I'm seeing this with my smart plugs (Heiman, Smartthings, ...) where it fails to update the energy monitored values (expected, as there is no converter associated)

![image](https://user-images.githubusercontent.com/85504/101478416-8e22b580-3948-11eb-8899-560c54398ae5.png)

**Comment by nurikk** [comment]
> Is this fixed in the latest z2m 1.16.2 ? I'm seeing this with my smart plugs (Heiman, Smartthings, ...) where it fails to update the energy monitored values (expected, as there is no converter associated)
> 
> ![image](https://user-images.githubusercontent.com/85504/101478416-8e22b580-3948-11eb-8899-560c54398ae5.png)

UI is rendered from exposes feature, currently, there are a lot of generic definitions. Feel free to raise PR to fine-tune your devices (in zigbee-herdman-converters repo)

**Comment by pedrolamas** [comment]
Just added a [PR on the zigbee-herdsman-converters](https://github.com/Koenkk/zigbee-herdsman-converters/pull/2084) to update the exposes access based on what there is or isn't part of the toZigbee bit! That should fix this issue compeltely!
