### ISSUE TITLE
[Bug]: Input field near slider does partially not working

### ISSUE THREAD

**Issue by vklachkov** [nurikk/z2m-frontend#1375]
### What happened?

I am developing my own zigbee thermostat. In the converter, in exposes, I wrote `climate()` with some field. Like this:

```js
exposes.climate()
    .withSystemMode(['off', 'auto'])
    .withLocalTemperature()
    .withLocalTemperatureCalibration(0.0, 2.5, 0.5)
    .withSetpoint('occupied_heating_setpoint', 15.0, 50.0, 0.5)
    .withEndpoint(epName),
```

If I enter values in the input field next to the slider, the value will not change until the focus is cleared from the field. But sometimes the value is not synchronized even after clicking on other controls. Strange behavior...

Additionally, the input field is not capable of fractional steps, just like the slider itself. I already reported this bug before

### What did you expect to happen?

The value entered in the field must be synchronized immediately after, without waiting for the focus to be removed 

### What browsers are you seeing the problem on?

Firefox, Chrome

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Value only sen't after input is loosing focus, this is intended behaviour, because user can try to set some parameter ex: `11.0` -> `22.5`, if we'll be sending request on every character change it will result into three(3) requests, taking in consideration is that zigbee device can be offline(sleepy) this is not desired behaviour, this is why frontend sends data only on [blur](https://developer.mozilla.org/en-US/docs/Web/API/Element/blur_event) event

**Comment by vklachkov** [comment]
It is possible to send a value with some debounce. Now defocus does not work intuitively. You enter a value - nothing happens, changed the tab, bam, it worked
