### ISSUE TITLE
[Bug]: Log/notification pop-up is in the way

### ISSUE THREAD

**Issue by tjarmann** [nurikk/z2m-frontend#1522]
### What happened?

The pop-up notifications on the right covers the menu, while running OTA on several devices they keep popping up and annoy me.
I had an issue where i got a button stuck in a loop, and the pop-up notifications were impossible to get rid of, and they covered parts of the screen that i needed to reach.

![image](https://user-images.githubusercontent.com/40260529/180235874-63f6cea9-d153-4886-a802-0716a0b58ba9.png)

I've googled without finding a way to disable this feature, so I'm reporting it. I hope there is a way to disable this, if there isn't i will report a feature request instead.

### What browsers are you seeing the problem on?

Chrome

### Did you download state.json.zip?

I will not attach state.json.zip

Edit: Typo

**Comment by Impact123** [comment]
Unstale.

**Comment by Impact123** [comment]
Unstale.

**Comment by Impact123** [comment]
Unstale.

**Comment by ChrisLane** [comment]
@nurikk this is still happening for me, even for a very slow update I still see notifications that are over 30 minutes old for the tab I've had open in the background.

Perhaps the fix for #1847 is no longer working?

Screenshot:
![image](https://github.com/user-attachments/assets/7a8f3dce-7797-4873-a925-7463126895a4)
