### ISSUE TITLE
Override image for devices

### ISSUE THREAD

**Issue by jacobvolstrup** [nurikk/z2m-frontend#193]
It would be nice to be able to override the image used for some of the devices, e.g. for use when some devices has been rebuild for other form factor than default image shows.

**Comment by nurikk** [comment]
Any ideas on how to implement this?

**Comment by jacobvolstrup** [comment]
A simple possibility to enter a URL for the image to use would be sufficient, very much like how a device is renamed now. Maybe the rename dialog could be changed to a "Settings" popup, and the having this as an extra available field?

**Comment by nurikk** [comment]
Currently, there is no API in z2m for this. Hence why I can not add this feature in frontend

**Comment by jacobvolstrup** [comment]
So for this to happen, I should first create a feature request for Z2M, which can afterwards be used in the frontend?

**Comment by nurikk** [comment]
Yes, correct. But tbh this isn't a mission-critical feature, so perhaps you might have to implement (by yourself) it in zigbee2mtt and then in fronted

**Comment by uncle-fed** [comment]
Here is a proposal how to possibly implement this feature in a "least invasive way".
Strictly speaking, a custom picture of a device does not belong to z2m API. 
It is only needed by the frontend component and it is never needed, when you don't use front-end.

So my idea is this: the information about custom picture should not be stored in the `configuration.yaml` (and later exposed through the API to the frontend. Instead, custom picture should only be a 'frontend' feature and should work independently from z2m API, this way:

- frontend configuration gets new parameter: something like `Custom web images path`.
- if this path is set, then frontend will try to look on the local filesystem of the web server for the device images, and if matching image is found there, it should be displayed instead of the one that comes from zigbee2mqtt.io web pages
- when the frontend is looking for the local custom image, it should look for it 2 different ways: first it should try and locate the file which has the `IEEE address` as the file name (and JPG or PNG extension), or, if such file does not exist, then it should try and look for the file name that has `manufacturer + model id` in the name (all non-alphanumeric characters and whitespace should be replaced by underscores, for example, all lowercase).

This logic will allow to have 1 custom image for all devices of the same model or individual files per each device, as needed.
I know this is not exactly what was requested (this is not a URL, you have to actually copy over images to your server where z2m is running), but this feature can two immediate benefits:

- it allows to be implemented immediately without any dependency on z2m API
- it allows to avoid to be dependent on the Internet resources for those images entirely, if desired

I see that actually z2m front-end still wants to load external internet resources, such as styles and fonts anyway. but maybe this is something that one day can give a way for complete offline operation for z2m frontend.

What do you think?

**Comment by nurikk** [comment]
I don’t want to implement this feature, but community contributions are welcome

**Comment by nurikk** [comment]
Implemented in latest dev
