### ISSUE TITLE
[Bug]: No logs in frontend

### ISSUE THREAD

**Issue by Clem-** [nurikk/z2m-frontend#1987]
### What happened?

No logs appear in frontend despite logging in container.

I am on latest dev branch.

### What browsers are you seeing the problem on?

Firefox

### Did you download state.json.zip?

Can't download state.json because of error:
> Uncaught (in promise) ReferenceError: require is not defined

**Comment by TheQue42** [comment]
Same issue here, on [1.37.1](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.37.1). Logs tab in frontend is effectively dead, regardless of debuglevel configured.
Same result in either firefox or edge. 

I did find the "Log debug to MQTT and frontend" setting in the advanced settings tab, but to spam my MQTT server with debug logs would be completely MAD.

**Comment by LaurentChardin** [comment]
Have a look at my answer here : https://github.com/Koenkk/zigbee2mqtt/issues/22522#issuecomment-2104370880

You can filter out some namespaces from the debug log and choose the ones you want to see.

**Comment by TheQue42** [comment]
@LaurentChardin But do I understand the text correctly? The debug logs will be sent TO the mqtt server, as MQTT messages? 

Why would I want to saturate my MQTT server with all those messages? And even if someone did, why merge the the options of sending logs to frontend **AND** mqtt server to _one_ setting?

**Comment by LaurentChardin** [comment]
> @LaurentChardin But do I understand the text correctly? The debug logs will be sent TO the mqtt server, as MQTT messages?
> 
> Why would I want to saturate my MQTT server with all those messages? And even if someone did, why merge the the options of sending logs to frontend **AND** mqtt server to _one_ setting?

@TheQue42 Ok let's be a bit more precise here. And this is what i understand when reading the code (i did not do the implementation). The websocket server is hooked on the internal event bus of z2m, listening to MQTT Published messages, and basically proxy those messages to the frontend. I believe this is why the developers introduced the possibility to filter out messages, to limit the numbers of messages sent. If you don't activate debug, i don't think you will *saturate* your mqtt server. However, if you activate debug mode, you probably really want to do a default filtering : at least the logs related to the zigbee drivers as those are really verbose. I agree that we should probably configured a default filtering by default.

From a design point of view, the frontend UI is just like any other client of z2m, the websocket controller could be directly listening to a mqtt server instead of the internal event bus. Really depends on what design strategy the project wants to have. You could have a log viewer directly in HomeAssistant without needed to use the frontend ui. A matter of choice in the end.

You can propose a change to the developers to change this behavior if it better suits your use-case. It can be possible to introduce an new message type in the event bus that is decoupled from the MQTT one, or fake a MQTT publish event without actually doing it :)
