### ISSUE TITLE
[Bug]: Renaming a device does not update entity names in HA

### ISSUE THREAD

**Issue by cloudbr34k84** [nurikk/z2m-frontend#2008]
### What happened?

In the past Frontend versions, when you renamed a device it had the option to rename the device in Home Assistant. That's now gone. WHen this was working it would also rename all the entities for the device. Now this doesn't anymore. Can we please have this back plus some of the other issues other users have reports
See image below of new device in MQTT in HA
![image](https://github.com/nurikk/zigbee2mqtt-frontend/assets/58960644/b552be56-055c-4bfe-98e9-b79ceb4aa294)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by smilisav** [comment]
There used to be a checkbox to rename HA entities when renaming a Zigbee2MQTT devices, but the option has disappeared since updating to 1.37.0 :( 

This affected me on HA 2024.4.latest, updating to HA 2024.5.0 didn't resolve it either.,

![image](https://github.com/nurikk/zigbee2mqtt-frontend/assets/13689196/369803be-6e9a-4777-8284-8fce14e45499)
