### ISSUE TITLE
[Bug]: Cannot update device settings via frontend

### ISSUE THREAD

**Issue by gitmulles** [nurikk/z2m-frontend#2080]
### What happened?

Trying to update device settings (e.g. checking 'retain' option), screen immediately updates with previous information.
(version 1.39)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Relevant stacktrace

```shell
no trace available
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by rrakso** [comment]
I can confirm. It is always "reloading" page.

**Comment by thargy** [comment]
I can also confirm.

As a workaround on Windows, if you click the setting (e.g., 'disable') and immediately press `enter` on the keyboard, you will click the default button on the page, saving the settings before the reload can occur. Otherwise, good luck trying to change the setting and clicking the button!

**Comment by RubenKelevra** [comment]
I can confirm it for 1.41.0.

> As a workaround on Windows, if you click the setting (e.g., 'disable') and immediately press `enter` on the keyboard, you will click the default button on the page, saving the settings before the reload can occur. Otherwise, good luck trying to change the setting and clicking the button!

Works on Linux, too.

Issue is: This does not work for adding elements to lists, like the "Filtered publish attributes", because you would need to hit plus, enter the name of the field and then hit enter within average 0.5 seconds.

So it definitely is blocking some functionality.

@Koenkk would be great if this could be fixed!

**Comment by gitmulles** [comment]
Here the workaround I use.  After loading device settings page, I go offline (e.g. wifi off) do the changes I need, save and immediately go online again.
Not really confortable, but easier than stopping zigbee and modifying config file manually.

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
