### ISSUE TITLE
[feature request] OTA page -- add current firmware version column

### ISSUE THREAD

**Issue by uncle-fed** [nurikk/z2m-frontend#331]
It would be super useful to be able to see the current firmware version information on the OTA page for each supported device in a separate column.

Thank you for your efforts!

**Comment by nurikk** [comment]
any practical application for this knowledge? Like okay, this device has version `9338.92m` and what's next?

**Comment by uncle-fed** [comment]
what can I say... I am a bit lost for words here.. 

I thought that when you're dealing with firmware updates of dozens of devices, especially on a separate dedicated page, having as much information relevant to this topic (i.e. "firmware") is a given thing, but what do I know? :-)

I suppose people are different and what seems most logical to one person may be the opposite for somebody else.  :-)

OK.. most simple example. I have 12 bulbs of the same maker, same model, bought over 2 years, so I ended up with 3 different firmware versions on the same hardware model. Maybe there is an known issue with some particular firmware version, and I would like to see and compare what bulbs are on what firmware version in which location.  "What's next?" Maybe I don't want to update something depending on this information, etc.

**Comment by nurikk** [comment]
I understand your point, but do you have any real examples?)
btw I don't mind you you add this feature and raise a PR

**Comment by uncle-fed** [comment]
the example I gave was very real.
I do have exactly situation like that with 12 lights.
I am still amazed we are having this discussion, to be honest.
if I knew I would have to write so much I would have already made a PR

**Comment by uncle-fed** [comment]
https://github.com/nurikk/z2m-frontend/pull/332

**Comment by timoline** [comment]
thx, I like  this addition

**Comment by CodeFinder2** [comment]
@nurikk I think the real benefit of having this feature is a) to lookup changelogs/changesets IF they are available for some device and b) to check the internet if there are any (bug) reports / forum posts about known problems with a specific device/firmware version.

That's why I like this feature as well! I would also appreciate to have a column showing the latest available firmware version (with the same reasoning as given above, i.e. to know *before* to what version I am going to upgrade). :-)
