### ISSUE TITLE
Dark Mode for mobile devices 

### ISSUE THREAD

**Issue by JoLander** [nurikk/z2m-frontend#367]
I'm using the frontend (especially the actual new version which provides a nice dashboard) often in a browser on my mobile device.
It would be nice to allow a dark mode setting with a dark (or black) background which becomes more and more common on mobile devices.

**Comment by kennymc-c** [comment]
+1

**Comment by juslex** [comment]
+1

**Comment by antti365** [comment]
+1
I support it, but I would like to see dark mode in the browser version, it's impossible to watch at night ...

**Comment by nurikk** [comment]
it's already in dev branch, welcome to test

**Comment by kennymc-c** [comment]
Just testet the new dark mode in the lastest version of zb2mqtt. But in fact it's a dark-blue mode than a dark/black mode. Especially mobile devices with OLED screens profit from real black tones since this saves battery live. GitHub also has this type of dark mode. Sorry for being a bit nitpicky but maybe this could be implemented.

**Comment by nurikk** [comment]
> Just testet the new dark mode in the lastest version of zb2mqtt. But in fact it's a dark-blue mode than a dark/black mode. Especially mobile devices with OLED screens profit from real black tones since this saves battery live. GitHub also has this type of dark mode. Sorry for being a bit nitpicky but maybe this could be implemented.

No plans for doing this
