### ISSUE TITLE
Dev Console menu of a device does not allow to address a specific endpoint

### ISSUE THREAD

**Issue by lauralally** [nurikk/z2m-frontend#926]
I've joined a router device exposing more than one endpoint. On the relative Dev Console tab it is possible to select the cluster and the relative attribute to read/write, but it is not possible to select the destination endpoint (it seems that at each join the choice is casual). It would be very helpful to have this possibility.

**Comment by nurikk** [comment]
Hi, @lauralally 
I've checked z2m api, and it seems that currently it doesn't support reading/writing attributes from particular endpoint. The main problem is that we need to read data from endpoint by number, not name (since we don't have information about all endpoint aliases on frontend).
https://github.com/Koenkk/zigbee2mqtt/blob/07a8a78a551f95ef345d97b4f5db79cb85318189/lib/extension/legacy/deviceGroupMembership.js#L6
Here is example log
```log
Received MQTT message on 'zigbee2mqtt/hue_back_tv/11/set' with data '{"read":{"attributes":["zclVersion"],"cluster":"genBasic","options":{}}}'
Error Entity 'hue_back_tv/11' is unknown
```
topicRegex - is quite tricky part of z2m, I'm not dare to tinker with it.

@Koenkk might help with it

**Comment by Koenkk** [comment]
@nurikk `zigbee2mqtt/hue_back_tv/11/set` should be fine, does `hue_back_tv` indeed have an endpoint 11? If it has, maybe this has already been fixed in the dev branch.

**Comment by nurikk** [comment]
> @nurikk `zigbee2mqtt/hue_back_tv/11/set` should be fine, does `hue_back_tv` indeed have an endpoint 11? If it has, maybe this has already been fixed in the dev branch.

I'm using latest `dev`, my device has endpoint `11` this is endpoint number, not one of enpointName from [publish.ts](https://github.com/Koenkk/zigbee2mqtt/blob/7086bc3e9dfe7d413ab4d6a3fa171e2bb9e82053/lib/extension/publish.ts#L12)

**Comment by lauralally** [comment]
Reading or writing by numbers it would be not a problem, at the end it is the same for the reporting or bind functionalities... but for the raw read and write it is not possible:

![Dev_Console_HASSIO](https://user-images.githubusercontent.com/3645356/136777443-6b6d6fed-17d3-41b3-b8ef-21f55b2568af.PNG)

**Comment by Koenkk** [comment]
@nurikk fixed now, publish by endpoint ID is also allowed now.

**Comment by nurikk** [comment]
> @nurikk fixed now, publish by endpoint ID is also allowed now.

Thanks 🙏 I’ve added endpoint picker to dev console page
